### ISSUE TITLE
Equal Area Under Curve Plot

### ISSUE THREAD

**Issue by Hamedloghmani** [fani-lab/Adila#37]
This issue is regarding the process of adding the equal area under curve plot feature to the pipeline
A sample is shown below:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/48960316/219273426-46353a19-48dd-4037-8acd-cd0ee868ef1f.png)

**Comment by hosseinfani** [comment]
@Hamedloghmani 
if this issue is resolved, pls close it.

**Comment by Hamedloghmani** [comment]
@hosseinfani 
Sure, I confirm that this issue is done. I'll close it in a moment. 
Thank you.
