### ISSUE TITLE
Adding  dblp, uspt, github Datasets to the Pipeline

### ISSUE THREAD

**Issue by Hamedloghmani** [fani-lab/Adila#40]

**Comment by Hamedloghmani** [comment]
Running the code in main branch on dblp dataset:

1. Greedy
- [ ]  bnn (running)
- [ ] bnn_emb(running)
- [ ] random(running)
2. Cons
- [ ] bnn (pending)
- [ ] bnn_emb(pending)
- [ ] random(pending)

3. Relaxed
- [ ] bnn (pending)
- [ ] bnn_emb(pending)
- [ ] random(pending)

**Comment by hosseinfani** [comment]
@Hamedloghmani 
- Random baseline is one time, right?

- After dblp, schedule uspt since it already has the gender labels. Since we want to do gender bias as well, right?

**Comment by Hamedloghmani** [comment]
@hosseinfani 
Thank you for your response.

- Since random baseline runtime is not that time consuming, I thought maybe it's better to run all 3 different algorithms on it as other baselines. Although the outcome will be almost the same.
- Sure, I will schedule uspt while we are inferring the genders for dblp as well. The plan is to make a case study both on popularity and gender. Do we have the outputs of OpeNTF for uspt ?

**Comment by hosseinfani** [comment]
@Hamedloghmani 
- what does random baseline do? or random baseline of opentf?

- yes we have. it's in opentf channel, opentf0.1/output/patent.*

**Comment by Hamedloghmani** [comment]
@hosseinfani 

-  I believe it will randomly assign experts to teams. My idea for running 3 re-ranking algorithms on it is to see how different det_greedy, det_cons and det_relaxed act on random baseline. Am I right ?
- Thank you so much. I'll download and schedule.

**Comment by hosseinfani** [comment]
@Hamedloghmani 
so, it's random baseline from opentf. yes, we can do that.
