### ISSUE TITLE
Zero before/after NDKL for every input after code refactor

### ISSUE THREAD

**Issue by Hamedloghmani** [fani-lab/Adila#51]
Today I have been struggling with this issue while trying to run my experiment for double cutoff method based on the refactored code. NDKL is always zero for every input.
I am prioritizing the task of resolving this bug.

**Comment by Hamedloghmani** [comment]
My initial experiments show this might be because of a math function in conda.

**Comment by Hamedloghmani** [comment]
@hosseinfani 
Cause:
reranking.ndkl function does not work with bool values. We changed the popularity labels to bool in refactor.

Solution:
Change the popularity labels to  'p' and 'np' or string version of true/false

**Comment by hosseinfani** [comment]
Pls convert it in L#81-82

**Comment by hosseinfani** [comment]
@Hamedloghmani I'm fixing it ...

**Comment by Hamedloghmani** [comment]
@hosseinfani 
I already fixed it last night. Please wait for the push.

**Comment by hosseinfani** [comment]
@Hamedloghmani 
I pushed my changes. You pull. The reason was not about working with bool. See the message of the push and the change.
Next time, please root cause the problem :)

**Comment by Hamedloghmani** [comment]
Sure, sorry for the inconvenience. :)
