### ISSUE TITLE
Summary of an Unsuccessful Attempt with Double-cutoff Method

### ISSUE THREAD

**Issue by Hamedloghmani** [fani-lab/Adila#60]
### Problem:
Our results in ECIR-Bias2023 (issue #34) suggest that deterministic greedy re-ranking algorithms are not successful in avoiding utility loss while maintaining fairness in different teams.
### Proposed Solution:
Our proposed solutions for this was the double-cutoff method that I'll explain with an example.
Suppose we need a team of 5 experts and we have the output by the size of 20 from the team formation baseline. Instead of passing 20 people to re-ranker, we first sort them by probability/score, select the top 10, then pass those to the re-ranker algorithm with k=5. We were planning to keep less related individuals out of the re-ranker's reach.
### Causes of Failure
This attempt was not successful since the main cause of utility loss was sparsity of our search space compared to the search space that these algorithms were originally developed on. Det_greedy, det_cons and det_relaxed work in an iterative manner and in each iteration they select the expert with highest popularity/score from the set of experts with under represented sensitive attribute. Hence, our solution was not helpful for this issue.
The sparsity problem will be more clear after finishing our analysis on other datasets and search spaces (#40)

**Comment by hosseinfani** [comment]
@Hamedloghmani 
afaik, in the pseudo code for detgreedy in the paper, they consider the prob when reranking, e.g,. L#7 in Algorithm 1. I think we only pass p/np to the reranker function. Sth is missing here.

**Comment by Hamedloghmani** [comment]
@hosseinfani 
My logic does not actually make sense, since I did not consider the iterative greedy approach of algorithms. I simply thought removing half of least relevant experts in each team and then re-rank would help.
I just documented it since you kindly suggested. At least no one would try it this way. 😅
